name: React CI/CD Workflow
on:
  push:
    branches:
      - dev

env:
  AWS_REGION: ap-northeast-2
  REACT_AWS_S3_BUCKET: luckyweeky-dev-bucket

jobs:
  deploy-react:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for React
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.2"

      - name: Build React project
        run: |
          npm install --legacy-peer-deps --loglevel=error
          CI=false npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CICD_SECRET_KEY }}

      - name: Upload React build to S3
        run: aws s3 sync build/ s3://${{ env.REACT_AWS_S3_BUCKET }}/
